# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180504_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
