# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closerice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
