# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closerice', '0002_auto_20180607_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='wifi',
        ),
    ]
