# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closerice', '0003_remove_restaurants_wifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='image',
            field=models.ImageField(blank=True, upload_to='imageforrestaurant'),
        ),
    ]
